apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-db
  namespace: chat-app
  labels:
    app: chat-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: chat-db
    spec:
      containers:
        - name: chat-db
          image: us-central1-docker.pkg.dev/microservices-chat-496017/chat-platform-cluster-registry/chat-db:36b3dfdc890195a75e7c4cfee7f541110640b91a
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: chat-db-secret
                  key: SECRET_KEY
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: chat-db-secret
                  key: SQLALCHEMY_DATABASE_URI
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
