apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-svc
  namespace: chat-app
  labels:
    app: chat-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: chat-svc
    spec:
      containers:
        - name: chat-svc
          image: us-central1-docker.pkg.dev/microservices-chat-496017/chat-platform-cluster-registry/chat-svc:2331adf0496e1f7b4077d8031f2257d72d433d08
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: chat-db-secret
                  key: SECRET_KEY
            - name: CHAT_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: chat-db-secret
                  key: CHAT_DB_HOST
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
