pyms:
  services:
    swagger:
      path: "swagger"
      file: "swagger.yaml"
    tracer:
      client: "jaeger"
      host: "localhost"
      component_name: "Chat DaaS"
  config:
    DEBUG: false
    TESTING: false
    APP_NAME: project
    APPLICATION_ROOT: ""
    SQLALCHEMY_TRACK_MODIFICATIONS: false
    SECRET_KEY: ${SECRET_KEY}
    SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
