apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-ingress
  namespace: chat-app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    # ADDED: Sticky sessions for Socket.IO
    # Routes all requests from same browser
    # to the same chat-svc pod
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "chat-svc-affinity"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chatms.store
        - www.chatms.store
      secretName: chat-tls
  rules:
    - host: chatms.store
      http:
        paths:
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: chat-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-front
                port:
                  number: 80
    - host: www.chatms.store
      http:
        paths:
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: chat-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-front
                port:
                  number: 80
