apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-front
  namespace: chat-app
  labels:
    app: chat-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-front
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: chat-front
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: chat-front
          image: us-central1-docker.pkg.dev/microservices-chat-496017/chat-platform-cluster-registry/chat-front:e051cdd618e8769965a1b1fa1e40d4711c5ce20c
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: chat-db-secret
                  key: SECRET_KEY
            - name: CHAT_SVC_HOST
              valueFrom:
                secretKeyRef:
                  name: chat-db-secret
                  key: CHAT_SVC_HOST
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
