pyms:
  services:
    requests:
      data: ""
  config:
    DEBUG: false
    TESTING: false
    APP_NAME: project
    APPLICATION_ROOT: /
    SECRET_KEY: ${SECRET_KEY}
    service_host: ${CHAT_SVC_HOST}
